heat_template_version: ocata
resources:
  workflow:
    type: OS::Mistral::Workflow
    properties:
      type: direct
      tasks:
        - name: task1
          action: mistral.environments_get name='ssh_keys'
          publish:
            env: <% task(task1).result.variables %>
          on_complete: [task2]
        - name: task2
          action: std.echo output=<% $.env %>
  execution:
    type: OS::Mistral::ExternalResource
    properties:
      actions:
        CREATE:
          workflow: {get_resource: workflow}

